dirs:
    experiment_dir: "./experiments/"
    data_dir: "./data/"
    model_dir: "./data/models"
paths:
    train_path: "./data/train.csv"
target_name: "churn"
important_vars: [
    'state',
    'international_plan',
    'voice_mail_plan',
    'number_vmail_messages',
    'number_customer_service_calls',
    'total_minutes',
    'total_charge'
]
possible_classifiers:
    [
        "GaussianNB", "LogisticRegression", "DecisionTreeClassifier"
    ]
random_classifiers:
    [
        "DecisionTreeClassifier"
    ]
seeds:
    train: 14